language: node_js
node_js:
- node
sudo: false
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: NxKfpHoPCS77rdkMevWOvRtcbXpg1geoy0w1ZJCwLBvuRBSpu9Oh0XMuY76QaxjtRwxSZANyb7wJDJfKuzqEK7kKEWPQGPsz45S1xcGR/hXqZL3cMHe18liu3M9Fl4ggcOP5Fflj/bOrcvocAAslcjGS0qF08p/imB74eLbnYNRmcg2FbdWJmry9f8gVZ2Oqq4MvItGsd157Sxnc3WCkElkOmkla+j4du8uSsYPd//ph83L5h0IcoObUDY3DZgQFQP91ZglpR6//fOZsqQuKq2+7m9p9joKT0nXKgNTe59HGwJs88vtn5V7TW16jq1sGnXodJ4SJuE0f38OLMD02UAUTwGVz1RFFea2vl/+BHhH4BbOfJxpFSDuFShE1KjDBo67hYPpForlTHjlk8sBRku4cgv/vLvTkmyC/TuckC1aBYqTCvSDut9UC7ry8LB5YrPvEp2qur5fzOm46f4TrahYOPLbjUUF4QbfiNIY9CXJb2RiImS6oMPfYw+hyMwZNgjI6J8+DYtM24Gl8Hu+Xhbsk4f/gqErpzJ8BmwwEDARP67UhJzjan/KcwwdJYWHkjENefUGNCA8RfsHIKoHWDLJNhkcfMC1hnVqiU5xR0HfxY6kLi+f5gfYl2KWy+8//vfYhD3ZKlrVAsuKVnJbPiNeGzjH+Wepw+itUP8q+qjY=
  app: devops--pipeline
  edge: true
