language: node_js
node_js:
- node
sudo: false
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: iF6XvqyZ+CzcO3kYb5pKxB3UbdSpMhuB+9/PkcKD0xjkpQlS2RbZz5g/hrWTxQCy2vGpEa+6X16RZMQbSQqnCTy6UPSsUnjabMv0ek6YMyV3/5r7O2cGyrODPOgQl/M7xtbUBrmB9/+iQdB2ts3/3pRzEZ92KkuBfRjGzDc0DYztkntmlgMT5oloo+v3Xw+OqQwn4cdyQE5WzIotmDDKgNxpgvIY0SLsFWhZrBQxkaXg8R1OLLiYo/zYYO/S8+wUwyuaWsGgLE2Efx0hS2FKKL4I7/V+IltG9ZfEAmR+BasZuIMnUmQzmQmRlNO34DN8Gf1x8mWJNT9yj0CmSxVojd64GY5SL7qMencQtQ9DUnfzy6fLNEFzaWUmUjh4IyTfQeq1g+w/PGa8BVhSIiI5TW6g0rccS5ja2CuBxZdZq0+0ME+uAwobLdj/Bag33Vz8T3iT/p01KNTluzw4+vTu1TL9+T+Q35Fs+16KFtVEpZl+b0PzdGOpakdw0p+2SPLhvBjIfLshDOAEe521/H5kTD17hwXYYZPtXmWZgde0YfpNmlsieVmlb0FBdElbRyUB+kybPc9JpnJw00p3eHpA0dBqaP6kbQPtHUbbEFJg9hJM3891U1GbP2CWsfo0J4uRsL2Hv6QNuyshWPPaw84gB62RNqr94PagECAdvDvHtdE=
  app: devops--pipeline
  edge: true
