language: node_js
node_js:
- node
sudo: false
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: B04XUh7VRjTxZt3BXahogoK9sq7/bFtzZ2FG7ePDYmQU+typ5wa9mTy7ZcnnhyzASv97vu5KFsW90bHczATIjFxnDMeAzMfeCuUo1d88NQlmqeEw+92vGSZcMfoFrV1xtX+IUS0V75GKR6lVegGXhLb/eyVinIWysMvL8sJMNfZh+xbyU7y84ZAtrftYst0s/02OaLjBouAJE7CJQhmbGT2RZD95MCqukePOqO/LfITbME8XQslV6CP2tQX/6pRd9kqh1/3C3ClCpL6sGChrBvURxDynz2i3lUfFHZWGDd7GbMY33j/ti6HK7mdMQuMe67mfO7EHmiQwMPqDB4pufosXf4kApshwlAM2gwHlh7zgoU2Smn8CLcw/cluKHm9cpcb1aniOCTW+a7k71azyRZspMn/yEEgeEAf7+9XaING8uom9gwRb8jHlungBXFOyBJKLkLncP0ENC77W9O1KwqEIDdD/Gcg4+WiY9CvYpnw1sVDqB2H/bpwLvisxSZ3s5RC2XAVt1LJNzfskyzRzPag+jtfCgHJjpQ0UjNUUOZ3w/rPzHsmpoq++DVt0AsDdc598mSWUSJYhfZnbM7VRZZUUFNTxN3XA2Ea3dfMyNCUgqMMi00WYSYIV/FNxFPths1fCbSB2JHQu/SzHygc8XHQKzBqLeraHfd8V+LuExVY=
  app: devops--pipeline
  edge: true
