language: node_js
node_js:
  - node
sudo: false
script:
  - npm test
deploy:
  provider: heroku
  api_key: WaCUVnz77EaUfH5mvJh0a/yX86FDeqAFq2wfxH1CVsC/8CxNkt/DB1zMrO3xLt3+4zh0Z36LdSQM/Iqfhv+W3HuyKII78VyqszY/v1VU5Ui+3eNc+cWaM9dSu92s/KAIIIvSprpL/4eaA2sKYJS2axRR2URJAyIleuqoXxLy5KqFZfQYwo8Z4CTrB751vaWziUFR+Fm8u130/PMuHeeXwlDbYB2Zi6LK/w+9vLG1QscCVHqI+dS8XXmy/potlFijSJ2vRWBfE6Uw7TzuHLhYxgpY3XJV4ermaOpx13bxRfWO7FNX/+eB4vi57EYnFbdvtfYbs7CxrksVrnNqJn0legjqoPJkD/lFtD2mksmQD8muq9rGI9xmswQit5WzVipOqF7dlJBJKUnIK40r5ER6+agJFL1RObAIIY4h7BljMcmheDIUb8YJVe31M4JcEMtA3tP8FRdotXD4TWCK/nUZqroSTXvwJ+2Uc+2iXBttnO0u3rP5hzTc3ukAA9P6e2WnmZhbisGFvishXz7f+BXdKOll+xltnip1VKjpg7fBK6p//RYcE9NciLn19m0rnaOLBDgSdr7AC6HMQUwvOlJOmIDHS7ikKyg3JxJGUi4jQR8b1qhcH9EG9p/c9iTU/hD3zOYpnBoqcVJuvGfsAIPibLFnNAb8Djtch9XKTYIGZlw=
    secure:
  app: devops--pipeline
  on:
      repo: MiguelRPG/DevOpsLab-Pipeline
