language: node_js
node_js:
  - node
sudo: false
script:
  - npm test
before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
deploy:
  provider: heroku
  api_key: $HEROKU_AUTH_TOKEN
  app: devops--pipeline
  on:
    repo: MiguelRPG/DevOpsLab-Pipeline
