language: node_js
node_js:
- node
sudo: false
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: Mv1C7NC+4/uYdX6u2QvgVkz2UlnLzAEL6x9Cm1bHlIun4WBce9gJCaBeozVCmeqdS6nAQa2gV1Fb1qddTanhYpLZa6uu5DWwVMXTDBmfESN2tMtVdVZtYmuwQDolWhLzDKeLhc0G9FCblZkQjJZrTjrBO6ehvIRnFiKGDowGQSya2vz44sHbBmaV+ZiEZyum9iCYPpPVn68rPR08+aE8mZYIPej+CqXkFSl+O/YuMwEutea6aw6TFml2zQfz6Vx68917AsdqzqoZSo864I0HTWdVlT0GLkzyWOQt4Ei7B6GTrorVeyy9T859++GmwwRW+MBfEs/WL8e7oE74w2ZAxPT7z1Mw4IJwMyLXEKJIO251wOpXP/UAz1+OJdciLxi57B1tv5Jv/e9ToScfEncImnyu5Qqw6Lkorzz2tISxC/rPMSc7pvqX+c4hOsJH6s7O0nVjQXi71YZKjSdzOFOubGANaTxDrHV4v3GR66jSw8mkzdeXH7L0TyVUxp+SFK1IM9i8vntfphtiwedYmR1l+aK7mzAMFe69fCbjC7hIn+kORbJa2/CEjbVsyYHGLbKpwLfoNSD/viePzrZzcMcCY1ameCy0Wt+Uw7YATjuT+g2qnjlGP8+MlG/g/5rI8aeDe4uWH3IEfJ/jfQkjZpsGMS43MVBodjISVnjyMtQgd4E=
  app: devops-ultimate
  edge: true
