language: node_js
node_js:
- node
sudo: false
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: Vk+DFoKtTbN5nxrJW1wyYA8qKeJSBDvv98UujecU6ZljXBMcMAXdBF1M+KHcw89L0ZwDh+4V382/y+80olCvqdVlThH8jYkE/O/BEeNM+tYVmOAv7lMyNmVf55WzI/CzD7IPoPFJTopj/9XtYDa3Dxikx5qhyuYchwYy4/SP3KN7DM6yIQWAzmf5kGAYmY/qpNe7GNJaFBGzqFJO0NtS6K7bUxycEpBb7qwQOIPwAFQsIUs9DUpX7e+bb7FE/bT1+TkI6QscuOYvEcrdc0vHK56kOrScgP4yCBU/6HuoBsiiNVR15N0ImDgHx4BZ9JE3WKVpE8wqczTR0OP4M5b4sIZG44SE7KgLT7XIXhY3cx3r19JpCleIyW6f/oQHHSPpLHnNH2GdBoNxPJl7mbZGXwBZrjAMrZMlOM2BFSExyeSXLPBofzsrXkJ2AAW7jQUxgD9pQp21ylyt/WcVhc76GIwyNrBmppipTJhNydePdztb/Pm02FCT1uaMV+VYFRn4InCRQvYEnimgzyKYtaYjnmWn/KnjQvnHTVdPys4umQhfRq+6nBk2FSbcXajMFcYZFcrd4k6Pxhvt7V9nLTndJ1RoE5mesPYnMv+lquH4D7CDpnxYN3eNWeOH0hf1WtMVQL+hS7Tc85QzYJSO9F4xRE42sPp+CC7I5k+F7rbO7MA=
  app: devops--pipeline
  edge: true
